language: node_js
node_js:
- 7.7
script:
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAJEGO5NVCIBLNMZDA
  secret_access_key:
    secure: l7R40NTeVFaBz+sKMrbgjzfoDRUYux/phcKQbeOJWzmGnsHcrFkQeibwGyqH5/5eyHgEELPy/V7ZgEUygHB/GnaaH2SOTSVdv38gq0IhsILyUZ4/TjCCxW85jScQ3zfMnPJfA5kO4p0Bb2OKX5pV8335dCEVh9jHowK4H3pdg+P9rqteU5dKI99gNqU90tuhyX8wRe1NUNzlSQ27s+McaZ9OTRKyt+PtR7ya4Dl+BG7QIObivAnJrbl3gVN+g+tT/WBHhNQ/FuVL7SAs25E97qhyEEALYYyeCLvBonM2GtQ2DXVzs0ue/nJMvL3aZnp/4r9FfYzFkRGjeif4Myzh0EkskhmAotsw13JuevS+Y0bW1dp6+nML/CplhbxZfmoZoxTeRBl0xi0wK3U3DUVITf0p84dEJr9736tCTzmBl2Q7fbx9e/53jwQZV92yc5cxigt5wRZrSklx24KR6MsSQY5rMADxCxTVp3vAa6CHouSrrRwegxibKMx9x3lozVRdi7jolyqTQy5TUOvNnYB3gVYCmsEW7btd7dfFRe0VP1DnqX+gfXxKSbyRqq4t2MxDxNtXggSDYDLFQ+pFa6aX0Uqrx9G317GgRogo3y+tIsTGbQU1MbGwPZPJKyLEqML0F3K/4Np4bKNXbI0lvz7GLif+1YBnnz7cY+AeTTkxqTc=
  bucket: dung-beetle-bash-travis-builds
  local-dir: deploy
  upload-dir: is-it-safe
  acl: authenticated_read
  on:
    repo: DungBeetleBASH/is-it-safe
